server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  security:
    user:
      name: user
      password: password
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        filters:
          -SecureHeaders
#        - id: DIGITAL-MIDDLEWARE
#          uri: http://localhost:8088
#          predicates:
#            - Path=/api/v1/customers/**
#            - Path=/api/v1/dashboard/**
        ##predicates[1]: Path=/api/v1/dashboard/**


eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/