server:
  port: 8888
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
#          uri: file:///C:/Projects/config-server-repo
          uri: https://github.com/Abelinho/config-server-repo
          clone-on-start: true
          default-label: main

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/


